### ISSUE TITLE
"Error: Copying of text from this document is not allowed."

### ISSUE THREAD

**Issue by mx03** [MrKrisKrisu/REWE-eReceipt-Parser#7]
Parser can't parse "REWE-eBon.pdf" exception thrown: "Error: Copying of text from this document is not allowed.".

Can solved with preprocess the pdf with qpdf `qpdf inputpath.pdf --decrypt -- outputpath.pdf`.

Not sure if there are simpler way's to get around this problem, but makes sense to add this information to readme.md or direct implement this directly into this library.

**Comment by MrKrisKrisu** [comment]
I cannot verify this Issue. My receipts are parsed properly.
Do you have an document to test this?
